### ISSUE TITLE
Pin Designations

### ISSUE THREAD

**Issue by dcs-electronics** [microchip-pic-avr-examples/atmega4809-getting-started-with-gpio-mplab#1]
PORTB.OUT |= PIN5_bm;     on the led tutorial - Where is the pin physically on the 40 pin atmega4809 ?

**Comment by pic-avr-github-admin** [comment]
Hi, according to the ATmega4809 datasheet that is pin is only available on the 48-pin packages. One will have to choose a different pin if using the 40-pin package.
